spring.application.name=findBugsProject
server.servlet.contextPath=/pop/dancers
jasypt.encryptor.bean=encryptorBean
encryptor.password=
server.port=8087
spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:23818/railway?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=ENC(y23bzIoW0fvbd5Huw1pxITFkTYQu6/5IefttxIEB0PhhwoV1XqNygCnQkgmdkOXI)
spring.datasource.password=ENC(BeraeT6vNSKGp63UZh3FSNQbzm1qj0uOnbFysa6yZs9fmkoGw12WaoMIHFKQo3YaenrDL6A08HGcVpXZS52NnM3j8VNV5qlLlcvic4VVTfE=)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

